vaultType: plain
services:
  influxdb:
    databaseName: sensorCLI
    # The token is retrieved from vault
    tokenSecret: influxToken
    serviceName: influxdb
    org: org
    bucket: bucket
    port: "8086"
  postgresdb:
    databaseName: sensorCLI
    # The secret is retrieved from vault
    passwordSecret: postgreSecret
    serviceName: postgredb
    sslmode: disable
    port: "5432"
  mailsender:
    serviceName: mailsender
    port: "8083"
security:
  authentication:
    JWT:
      jwtAudienceSecret: audSecret
      jwtIssuerSecret: issSecret
      jwtSigningKey: signingKey
      expirationTime: 1h
  #If tls configuration is not provided HTTP server communication is configured
  tls:
    #The cert file is read from ./cfg/tls directly.
    #If the certificate is signed by a certificate authority,
    #the certFile should be the concatenation of the server's certificate,
    #any intermediates, and the CA's certificate.
    certFile: sensorapiCert.pem
    #The matching for the certificate private key.
    privateKey: sensorapiKey.pem
    rootCACert: rootCACert.pem
    rootCAKey: rootCAKey.pem
user:
  userSecret: "userSecret"
  firstname: "Todor"
  lastname": "Todorov"
  email: "todor.mtodorov01@gmail.com"

