influxdb:
  databaseName: sensorCLI
  # The token is retrieved from vault
  tokenSecret: influxToken
  serviceName: influxdb
  org: org
  bucket: bucket
  port: "8086"
postgresdb:
  databaseName: sensorCLI
  # The secret is retrieved from vault
  passwordSecret: postgreSecret
  serviceName: postgredb
  sslmode: disable
  port: "5432"
mailsender:
  serviceName: mailsender
  port: "8083"
authorization:
  JWT:
    jwtAudienceSecret: audSecret
    jwtIssuerSecret: issSecret
    jwtSigningKey: signingKey
    expirationTime: 1h
vaultType: plain
