version: '3.8'
services:
  influxdb:
    image: todorov99/influxdb:1.0.0
    container_name: "influx-bachelor"
    ports: 
      - '8086:8086'
  postgredb:
    image: todorov99/postgredb:1.0.2
    container_name: "postgre-bachelor"
    ports:
      - '5432:5432'
  server:
    image: todorov99/server:1.0.1
    container_name: "server-bachelor"
    depends_on:
      - 'influxdb'
      - 'postgredb'
    ports:
      - '8081:8081'